hints = {
    1: "It's the first positive integer, and the identity element for multiplication.",
    2: "It's the only even prime number.",
    3: "It's the number of sides on a triangle and the first odd prime.",
    4: "It's the first composite number and the square of the first even prime.",
    5: "It's the number of fingers on one hand and the points on a pentagon.",
    6: "It's the smallest perfect number.",
    7: "It's the number of days in a week and often considered lucky.",
    8: "It's the cube of the first even prime.",
    9: "It's the square of the first odd prime.",
    10: "It's the base of our everyday number system.",
    11: "It's a palindrome and a prime number.",
    12: "It's the number of months in a year and inches in a foot.",
    13: "It's a prime number often associated with bad luck.",
    14: "It's the number of days in two weeks.",
    15: "It's the sum of the first three prime numbers.",
    16: "It's a perfect square and a power of two.",
    17: "It's a prime number.",
    18: "It's twice the number of a dozen.",
    19: "It's a prime number.",
    20: "It's two decades.",
    21: "It's a triangular number and a Fibonacci number.",
    22: "It's a composite number, twice eleven.",
    23: "It's a prime number.",
    24: "It's the number of hours in a day.",
    25: "It's a perfect square and the number of cents in a quarter.",
    26: "It's the number of letters in the English alphabet.",
    27: "It's a perfect cube.",
    28: "It's the second perfect number.",
    29: "It's a prime number.",
    30: "It's the number of days in April, June, September, and November.",
    31: "It's a prime number.",
    32: "It's a power of two and the number of teeth in an adult human's mouth.",
    33: "It's a multiple of three and eleven.",
    34: "It's the number of states in the USA (currently).",
    35: "It's a multiple of five and seven.",
    36: "It's a perfect square and a multiple of six.",
    37: "It's a prime number.",
    38: "It's twice nineteen.",
    39: "It's a multiple of three and thirteen.",
    40: "It's four times ten.",
    41: "It's a prime number.",
    42: "It's a significant number in a popular sci-fi novel.",
    43: "It's a prime number.",
    44: "It's four times eleven.",
    45: "It's a multiple of five and nine.",
    46: "It's twice twenty-three.",
    47: "It's a prime number.",
    48: "It's the number of months in six years.",
    49: "It's the square of seven.",
    50: "It's half of a century.",
    51: "It's a multiple of three and seventeen.",
    52: "It's the number of weeks in a year.",
    53: "It's a prime number.",
    54: "It's six times nine.",
    55: "It's a multiple of five and eleven.",
    56: "It's seven times eight.",
    57: "It's a multiple of three and nineteen.",
    58: "It's twice twenty-nine.",
    59: "It's a prime number.",
    60: "It's the number of minutes in an hour.",
    61: "It's a prime number.",
    62: "It's twice thirty-one.",
    63: "It's seven times nine.",
    64: "It's a perfect eighth power and a perfect square.",
    65: "It's a multiple of five and thirteen.",
    66: "It's six times eleven.",
    67: "It's a prime number.",
    68: "It's four times seventeen.",
    69: "It's a multiple of three and twenty-three.",
    70: "It's seven times ten.",
    71: "It's a prime number.",
    72: "It's the number of squares on a chessboard.",
    73: "It's a prime number.",
    74: "It's twice thirty-seven.",
    75: "It's three-quarters of a century.",
    76: "It's four times nineteen.",
    77: "It's seven times eleven.",
    78: "It's six times thirteen.",
    79: "It's a prime number.",
    80: "It's eight times ten.",
    81: "It's the square of nine.",
    82: "It's twice forty-one.",
    83: "It's a prime number.",
    84: "It's twelve times seven.",
    85: "It's five times seventeen.",
    86: "It's twice forty-three.",
    87: "It's a multiple of three and twenty-nine.",
    88: "It's eight times eleven.",
    89: "It's a prime number.",
    90: "It's nine times ten.",
    91: "It's seven times thirteen.",
    92: "It's four times twenty-three.",
    93: "It's a multiple of three and thirty-one.",
    94: "It's twice forty-seven.",
    95: "It's five times nineteen.",
    96: "It's eight times twelve.",
    97: "It's a prime number.",
    98: "It's two times forty-nine.",
    99: "It's nine times eleven.",
    100: "It's a perfect square and represents a full century.",
}
