name: Release Task Tracker

on:
  push:
    tags:
      - TaskTracker

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --noconsole task_tracker.py

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: Task Tracker Release
          tag_name: TaskTracker
          files: dist/task_tracker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
